### PR TITLE
adds em conversion function for ease

### PR DESCRIPTION
**Pull request by furzeface**
Something I find useful. It means you can take pixel values from PSDs etc and just throw them in, and they get converted to `em`s. Keep it if you like!

### CODE REVIEW

**Comment by phildotdev** [comment]
At first I was torn with this as I have a postcss task for converting values to rem but I think this is a good idea for things like the variables.scss file so I am very happy to merge this in.

Thanks @furzeface.

**Comment by furzeface** [comment]
Yeah man, that's exactly what it's for - like the example in the `_variables.scss`, just for ease of manually converting pixel values from designs into `em`s :smile:

**Comment by phildotdev** [comment]
@furzeface thanks for this! merged now

**Comment by furzeface** [comment]
:octocat:

**Pull request merged**
