### PR TITLE
feat: implement visual regression testing into workflow, resolves 19

### PR DESCRIPTION
**Pull request by furzeface**
:octocat:

### CODE REVIEW

**Comment by phildotdev** [comment]
This is awesome. Got some time pencilled in to get this integrated but thank you!

**Comment by furzeface** [comment]
I'm going to update this to the latest version to get rid of dependency of `gulp-chug`, as per: https://github.com/furzeface/furzeface.com-v4/blob/master/tasks/testing.js#L11

**Comment by phildotdev** [comment]
Why is this closed? This is still a priority.

**Comment by furzeface** [comment]
Going to redo this functionality, it it's pretty out of date now and I've found much better ways to do it! :octocat:

**Comment by phildotdev** [comment]
Yes pal! Sexy panda 🐼

**Pull request closed without merging**
